[package]
name = "hermetica"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
bytemuck = "1.16.1"
rpassword = "7.3.1"
indicatif = "0.17.8"

[build-dependencies]
nasm-rs = "0.3.0"
cc = "1.0.99"


